"""
agents/gitops_bridge.py — GitHub PR creation for approved remediations.

Called by policy_review_agent when OPA approves a remediation.
Creates a branch, commits the patch, and opens a PR.

Environment variables required:
  GITHUB_TOKEN  — Personal Access Token with repo:write scope
  GITHUB_REPO   — Repository in "owner/repo" format (e.g. "gauravpandey/sentinelops")

Exit check:
  Set GITHUB_TOKEN and GITHUB_REPO, then run:
    python -c "
    from agents.gitops_bridge import open_remediation_pr
    url = open_remediation_pr(
        repo_name='<username>/sentinelops',
        incident_id='test-abc123',
        file_path='gitops/manifests/sample-app-deployment.yaml',
        new_content='# test patch content',
        rca_summary='Memory leak detected in sample-app',
        risk_level='medium'
    )
    print('PR URL:', url)
    "
"""

import logging
import os

from github import Github, GithubException

log = logging.getLogger("gitops-bridge")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO  = os.getenv("GITHUB_REPO",  "<your-username>/sentinelops")
BASE_BRANCH  = "main"

# Auto-merge only for low risk — set to False to always require human review
AUTO_MERGE_LOW_RISK = os.getenv("AUTO_MERGE_LOW_RISK", "false").lower() == "true"


def open_remediation_pr(
    repo_name: str,
    incident_id: str,
    file_path: str,
    new_content: str,
    rca_summary: str = "",
    risk_level: str = "medium"
) -> str:
    """
    Create a GitHub branch + commit + PR for an approved remediation patch.

    Args:
        repo_name:   Full repo name "owner/repo".
        incident_id: Incident UUID used as branch name suffix.
        file_path:   Repo-relative path to the manifest file to update.
        new_content: New file content (the patched manifest YAML).
        rca_summary: Truncated RCA text — included in PR body for audit trail.
        risk_level:  "low" | "medium" | "high" — included in PR body.

    Returns:
        PR HTML URL string on success.
        Raises RuntimeError on failure.
    """
    if not GITHUB_TOKEN:
        raise RuntimeError(
            "GITHUB_TOKEN environment variable not set. "
            "Create a token with repo:write scope and export GITHUB_TOKEN=<token>"
        )

    g    = Github(GITHUB_TOKEN)
    repo = g.get_repo(repo_name)

    branch_name = f"auto-fix/{incident_id}"

    # ── Create branch from main ───────────────────────────────────────────────
    try:
        source_sha = repo.get_branch(BASE_BRANCH).commit.sha
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source_sha)
        log.info("Created branch: %s (from %s @ %s)", branch_name, BASE_BRANCH, source_sha[:8])
    except GithubException as exc:
        if exc.status == 422:
            # Branch already exists — idempotent, continue
            log.warning("Branch %s already exists — reusing", branch_name)
        else:
            raise RuntimeError(f"Failed to create branch {branch_name}: {exc}") from exc

    # ── Commit patched file to the branch ─────────────────────────────────────
    try:
        existing = repo.get_contents(file_path, ref=BASE_BRANCH)
        repo.update_file(
            path=file_path,
            message=f"fix(auto): remediate incident {incident_id[:8]}",
            content=new_content,
            sha=existing.sha,
            branch=branch_name
        )
        log.info("Committed patch to %s:%s", branch_name, file_path)
    except GithubException as exc:
        raise RuntimeError(f"Failed to commit file {file_path}: {exc}") from exc

    # ── Open Pull Request ──────────────────────────────────────────────────────
    pr_body = f"""## 🤖 SentinelOps Auto-Remediation

**Incident ID**: `{incident_id}`
**Risk Level**: `{risk_level}`
**File Changed**: `{file_path}`

### Root Cause Analysis
{rca_summary or '_No RCA available_'}

### Remediation
This PR was generated automatically by the SentinelOps LangGraph pipeline after passing OPA policy review.

{"⚠️ **Manual review required** — risk level is **medium or higher**." if risk_level != "low" else "✅ Low-risk change — eligible for auto-merge."}

### How to Rollback
Revert this PR: `git revert HEAD~1` on the `main` branch.
Argo CD will detect the revert and re-sync the cluster within its sync interval.

---
_Generated by SentinelOps_ | [Runbook](../../docs/runbook.md)
"""

    try:
        pr = repo.create_pull(
            title=f"🔧 Auto-remediation: incident {incident_id[:8]} [{risk_level} risk]",
            body=pr_body,
            head=branch_name,
            base=BASE_BRANCH
        )
        log.info("PR created: %s (number=#%d)", pr.html_url, pr.number)
    except GithubException as exc:
        raise RuntimeError(f"Failed to create PR: {exc}") from exc

    # ── Auto-merge low-risk PRs (if enabled) ──────────────────────────────────
    if AUTO_MERGE_LOW_RISK and risk_level == "low":
        try:
            pr.merge(
                commit_title=f"Auto-merged: remediation for incident {incident_id[:8]}",
                merge_method="squash"
            )
            log.info("Auto-merged PR #%d (low risk)", pr.number)
        except GithubException as exc:
            log.warning("Auto-merge failed (requires branch protection rules?): %s", exc)

    return pr.html_url
